name: laps
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.7
  - black
  - cairocffi
  - cffi
  - dill
  - docopt
  - frozendict
  - graphviz
  - imageio
  - jedi
  - Jinja2
  - joblib
  - jsonschema
  - jupyterlab
  - matplotlib
  - multiprocess
  - nltk
  - num2words
  - numpy
  - openai
  - pandas
  - pandocfilters
  - pathspec
  - pathos
  - Pillow
  - pip
  - pre-commit
  - protobuf
  - pycairo
  - Pygments
  - pyparsing
  - pytest
  - python-dateutil
  - pytorch
  - pyzmq
  - regex
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - sexpdata
  - six
  - terminado
  - toml
  - torchvision
  - tornado
  - tqdm
  - transformers
  - typed-ast
  - typing-extensions
  - pip:
    - mypy-extensions
    - phx-class-registry
    - pregex
    - pytorch-nlp
    - stitch_core
